apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgBPDJXrt5J6JwNpntvQH23yyjHsOrF4YTBPBEIiH442kUrR3gPAGn5ivoMTqeQDXn699PUSDbriZD5hqHI1legtkIiFEP7tXgiC1jAWdmv1GESoFz8xsvnYjlTJQ9x1vbAHsr87wConrirURmGgjXSxdDuTSEixaELeO6Ho3/uKPKXgPZ+6loVPhGlVmdtf3HreTIh74K9lkMW7aTj+kQDwJZdbItABvd6hVmh6d8NIeEUx2MCSjuxxfbMX+/NX6n+qW3jE10APrEIFaMe/6E28kP/65Izwx0ZhqWecj28KuIMtMhAMQM5mSm+bf4JZtvBiAD/vZaSgm7PljkljCJGjTAvLJANcPCaMn0Nz3T4I6/OHYwlmdC6b0NPgTuGTVA0kKUT5JevZfUUo9CHlXuoQ1s14QYrqHs8bPl4+CJdfXwQXFr/5MYx1EXWKx1NT+w6sytSxh5zO9L8SgZ2JvpDQpvLCAORPqSb1OsGrt8s4Dxe4IQ8l3iGhAGi/Gerl1WZAzGPuAwKD0jFadvQXVePXhyArk3ffagYYhoxhc1zEPWaxzbw9C8luBaCBKgLpSQ1tqTVu8mf1p4UsGXAcLsIBG0dAIa6tfIKHVPHLgYmUNW+fVdMAeeH4Ymm0y153It8of7Jx9QjWfyxutReBvMwe05ByQmyGuU8GqKyfS23COdH/UNoC4dYcwN/kVr3mwbhRmppVukAFl6EPdqk=
